# Corne v4 (nRF52840) — 2x550mAh, không LED, hotswap choc/MX

# Deep sleep: ZMK mặc định TẮT. Bật để pin 1100mAh trụ được nhiều tuần.
CONFIG_ZMK_SLEEP=y

# Bàn phím không hỗ trợ LED -> để nguyên tắt
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Chỉ bật nếu bạn có gắn màn OLED (tốn pin, vô ích nếu không có)
# CONFIG_ZMK_DISPLAY=y
